### ISSUE TITLE
Crash on big data, how to paging ?

### ISSUE THREAD

**Issue by alfiansetia** [ShafiqSadat/RouterOSClient#1]
example: i have 1000 data user hotspot on mikrotik, how to paging that ?
because my app was stopped if i get on big data.

**Comment by ShafiqSadat** [comment]
Can you send me logs?

**Comment by alfiansetia** [comment]
this is image result on error
![image](https://github.com/user-attachments/assets/455ee842-28e7-4757-9071-dfabdecf09f9)
Error._throw (c:\flutter\bin\cache\pkg\sky_engine\lib\_internal\vm\lib\errors_patch.dart:27)
Error.throwWithStackTrace (c:\flutter\bin\cache\pkg\sky_engine\lib\core\errors.dart:120)
_rootHandleError.<anonymous closure> (c:\flutter\bin\cache\pkg\sky_engine\lib\async\zone.dart:1386)
_microtaskLoop (c:\flutter\bin\cache\pkg\sky_engine\lib\async\schedule_microtask.dart:40)
_startMicrotaskLoop (c:\flutter\bin\cache\pkg\sky_engine\lib\async\schedule_microtask.dart:49)

Error._throw (c:\flutter\bin\cache\pkg\sky_engine\lib\_internal\vm\lib\errors_patch.dart:27)
Error.throwWithStackTrace (c:\flutter\bin\cache\pkg\sky_engine\lib\core\errors.dart:120)
_rootHandleError.<anonymous closure> (c:\flutter\bin\cache\pkg\sky_engine\lib\async\zone.dart:1386)
_microtaskLoop (c:\flutter\bin\cache\pkg\sky_engine\lib\async\schedule_microtask.dart:40)
_startMicrotaskLoop (c:\flutter\bin\cache\pkg\sky_engine\lib\async\schedule_microtask.dart:49)

Error._throw (c:\flutter\bin\cache\pkg\sky_engine\lib\_internal\vm\lib\errors_patch.dart:27)
Error.throwWithStackTrace (c:\flutter\bin\cache\pkg\sky_engine\lib\core\errors.dart:120)
_rootHandleError.<anonymous closure> (c:\flutter\bin\cache\pkg\sky_engine\lib\async\zone.dart:1386)
_microtaskLoop (c:\flutter\bin\cache\pkg\sky_engine\lib\async\schedule_microtask.dart:40)
_startMicrotaskLoop (c:\flutter\bin\cache\pkg\sky_engine\lib\async\schedule_microtask.dart:49)

Error._throw (c:\flutter\bin\cache\pkg\sky_engine\lib\_internal\vm\lib\errors_patch.dart:27)
Error.throwWithStackTrace (c:\flutter\bin\cache\pkg\sky_engine\lib\core\errors.dart:120)
_rootHandleError.<anonymous closure> (c:\flutter\bin\cache\pkg\sky_engine\lib\async\zone.dart:1386)
_microtaskLoop (c:\flutter\bin\cache\pkg\sky_engine\lib\async\schedule_microtask.dart:40)
_startMicrotaskLoop (c:\flutter\bin\cache\pkg\sky_engine\lib\async\schedule_microtask.dart:49)

Error._throw (c:\flutter\bin\cache\pkg\sky_engine\lib\_internal\vm\lib\errors_patch.dart:27)
Error.throwWithStackTrace (c:\flutter\bin\cache\pkg\sky_engine\lib\core\errors.dart:120)
_rootHandleError.<anonymous closure> (c:\flutter\bin\cache\pkg\sky_engine\lib\async\zone.dart:1386)
_microtaskLoop (c:\flutter\bin\cache\pkg\sky_engine\lib\async\schedule_microtask.dart:40)
_startMicrotaskLoop (c:\flutter\bin\cache\pkg\sky_engine\lib\async\schedule_microtask.dart:49)

**Comment by ShafiqSadat** [comment]
Can you check this command using winbox terminal?

**Comment by alfiansetia** [comment]
command working succesfully on winbox

![image](https://github.com/user-attachments/assets/84d2853a-4bad-4c27-ba0a-313c239a74dc)

this my code and working perfect if fetch small data (<200 data)

![image](https://github.com/user-attachments/assets/c20df963-a9b1-4807-a0aa-950168167dd8)

**Comment by ShafiqSadat** [comment]
I currently don't have the necessary data to test. Could you please provide a read-only user account for your router so I can connect and test the code with a larger dataset?

**Comment by ShafiqSadat** [comment]
If yes, please send me on telegram https://t.me/Shafiq

**Comment by ShafiqSadat** [comment]
Please check updated version:

router_os_client: ^1.0.4

**Comment by ShafiqSadat** [comment]
I will close this issue as resolved. If necessary, it can be reopened later.
