### ISSUE TITLE
talk method missed parameter 

### ISSUE THREAD

**Issue by sohrabezzati** [ShafiqSadat/RouterOSClient#2]
the talk method without ? befor params don't work fine but in this format works fine 

  if (params != null) {
      params.forEach((key, value) {
        sentence.add('?=$key=$value');
      });
    }
    
    
    this is for print queries otherwise works fine

**Comment by ShafiqSadat** [comment]
here is how you can talk with param and without param
# Without param
        client.talk('/interface/pppoe-client/print').then((value) {
          var user = value[0]['user'];
        });
        
 # With param
        await client.talk('/ip/firewall/address-list/add', {
          'list': 'FacebookBlock',
          'address': element,
          'comment': 'FacebookBlock',
        });
